INSERT INTO [dbo].[macs] ([Id], [Serialnumber], [mvBlueGEMINI], [BlfCam_Profinet], [BlfCam_TCP]) VALUES (23, N'MS000241', NULL, NULL, NULL)
INSERT INTO [dbo].[macs] ([Id], [Serialnumber], [mvBlueGEMINI], [BlfCam_Profinet], [BlfCam_TCP]) VALUES (23, N'MS000113', NULL, NULL, NULL)
INSERT INTO [dbo].[macs] ([Id], [Serialnumber], [mvBlueGEMINI], [BlfCam_Profinet], [BlfCam_TCP]) VALUES (23, N'160301893DE', NULL, NULL, NULL)
INSERT INTO [dbo].[macs] ([Id], [Serialnumber], [mvBlueGEMINI], [BlfCam_Profinet], [BlfCam_TCP]) VALUES (23, N'MS000105', NULL, NULL, NULL)
INSERT INTO [dbo].[macs] ([Id], [Serialnumber], [mvBlueGEMINI], [BlfCam_Profinet], [BlfCam_TCP]) VALUES (23, N'MS000240', NULL, NULL, NULL)
INSERT INTO [dbo].[macs] ([Id], [Serialnumber], [mvBlueGEMINI], [BlfCam_Profinet], [BlfCam_TCP]) VALUES (NULL, N'MS000101', NULL, NULL, NULL)
INSERT INTO [dbo].[macs] ([Id], [Serialnumber], [mvBlueGEMINI], [BlfCam_Profinet], [BlfCam_TCP]) VALUES (NULL, NULL, N'00:0c:8d:00:0c:f1', NULL, NULL)
INSERT INTO [dbo].[macs] ([Id], [Serialnumber], [mvBlueGEMINI], [BlfCam_Profinet], [BlfCam_TCP]) VALUES (NULL, NULL, N'00:0c:8d:00:0c:f1', NULL, NULL)
DELETE FROM [dbo].[macs] WHERE ( mvBlueGEMINI='00:0c:8d:00:0c:f1')
DELETE FROM [dbo].[macs] WHERE ( Serialnumber LIKE '%DE')